AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  document-describer

  Sample SAM Template for document-describer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  AnalyzeDocument:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt DynamoDBTable.Arn]]
          TABLE_HASH: "id"
          TABLE_RANGE: "block"
      Events:
        AnalyzeDocumentEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
      Policies:
        - Statement:
          - Sid: Comprehend
            Effect: Allow
            Action:
            - comprehend:DetectEntities
            - comprehend:BatchDetectEntities
            Resource: '*'
        - Statement:
          - Sid: Textract
            Effect: Allow
            Action:
            - textract:DetectDocumentText
            - textract:StartDocumentTextDetection
            - textract:StartDocumentAnalysis
            - textract:AnalyzeDocument
            Resource: '*'
        - Statement:
          - Sid: S3
            Effect: Allow
            Action:
            - s3:getObject
            - s3:getObjectVersion
            Resource: "*"
        - Statement:
          - Sid: DynamoDB
            Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:BatchWriteItem
            Resource: "*"
  SrcBucket:
    Type: AWS::S3::Bucket

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        - AttributeName: block
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
        - AttributeName: block
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
        StreamViewType: NEW_IMAGE


